export { default as Header } from './Header'
export { default as HeroSection } from './HeroSection'
export { default as PartnersSection } from './PartnersSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as ProcessSection } from './ProcessSection'
export { default as FAQSection } from './FAQSection'
export { default as CTASection } from './CTASection'
export { default as Footer } from './Footer'
